(*
   pyxc.ebnf
   Grammar for chapter 11 — Mutable variables.
*)

(*
   { } = zero or more (any number of...)
   [ ] = zero or one (optional)
*)

program         = [ end-of-lines ] [ top-level-item { end-of-lines top-level-item } ] [ end-of-lines ] ;
end-of-lines            = end-of-line { end-of-line } ;
top-level-item             = function-definition | decorated-function-definition | external | top-level-expression ;
function-definition      = "def" function-signature ":" [ end-of-lines ] expression ;
decorated-function-definition    = binary-decorator end-of-lines "def" binary-operator-signature ":" [ end-of-lines ] expression
                | unary-decorator  end-of-lines "def" unary-operator-signature  ":" [ end-of-lines ] expression ;
binary-decorator = "@" "binary" "(" integer ")" ;
unary-decorator  = "@" "unary" ;
binary-operator-signature = custom-operator-character "(" name "," name ")" ;
unary-operator-signature  = custom-operator-character "(" name ")" ;
external        = "extern" "def" function-signature ;
top-level-expression    = expression ;
function-signature       = name "(" [ name { "," name } ] ")" ;
ifexpr          = "if" expression ":" [ end-of-lines ] expression [ end-of-lines ] "else" ":" [ end-of-lines ] expression ;
forexpr         = "for" [ "var" ] name "=" expression "," expression "," expression ":" [ end-of-lines ] expression ;
expression      = varexpr | name "=" expression | unary-expression binary-operator-right ;
binary-operator-right        = { binary-operator unary-expression } ;
varexpr         = "var" variable-binding { "," variable-binding } ":" [ end-of-lines ] expression ;
variable-binding      = name [ "=" expression ] ;
unary-expression       = unary-operator unary-expression | primary ;
unary-operator         = "-" | user-defined-unary-operator ;
primary         = name-expression | number-expression | parenthesized-expression
                | ifexpr | forexpr ;
name-expression  = name | call-expression ;
call-expression        = name "(" [ expression { "," expression } ] ")" ;
number-expression      = number ;
parenthesized-expression       = "(" expression ")" ;
binary-operator        = builtin-binary-operator | user-defined-binary-operator ;
builtin-binary-operator = "+" | "-" | "*" | "<" | "<=" | ">" | ">=" | "==" | "!=" ;
user-defined-binary-operator = ? any operator-character defined as a custom binary operator ? ;
user-defined-unary-operator  = ? any operator-character defined as a custom unary operator ? ;
custom-operator-character    = ? any operator-character that is not "-" or a builtin-binary-operator,
                    and not already defined as a custom operator ? ;
operator-character          = ? any single ASCII punctuation character ? ;
name      = (letter | "_") { letter | digit | "_" } ;
integer         = digit { digit } ;
number          = digit { digit } [ "." { digit } ]
                | "." digit { digit } ;
letter          = "A".."Z" | "a".."z" ;
digit           = "0".."9" ;
end-of-line             = "\r\n" | "\r" | "\n" ;
comment = "#" { comment-character } ;
comment-character = ? any character except "\r" and "\n" ? ;
whitespace = " " | "\t" | "\v" | "\f" ;
