(*
   pyxc.ebnf
   Baseline grammar for chapter 4.
*)

(*
   { } = zero or more (any number of...)
   [ ] = zero or one (optional)
*)
program        = [ end-of-lines ] [ top-level-item { end-of-lines top-level-item } ] [ end-of-lines ] ;
end-of-lines           = end-of-line { end-of-line } ;
top-level-item            = function-definition | top-level-expression ;
function-definition     = "def" function-signature ":" [ end-of-lines ] expression ;
top-level-expression   = expression ;
function-signature      = name "(" [ name { "," name } ] ")" ;
expression     = primary binary-operator-right ;
binary-operator-right       = { binary-operator primary } ;
primary        = name-expression | number-expression | parenthesized-expression ;
name-expression = name
                 | name "(" [ expression { "," expression } ] ")" ;
number-expression     = number ;
parenthesized-expression      = "(" expression ")" ;
binary-operator       = "+" | "-" | "*" | "<" ;
name     = (letter | "_") { letter | digit | "_" } ;
number         = digit { digit } [ "." { digit } ]
                 | "." digit { digit } ;
letter         = "A".."Z" | "a".."z" ;
digit          = "0".."9" ;
end-of-line            = "\r\n" | "\r" | "\n" ;
(*
    `whitespace` may appear between any two tokens
     and is ignored by the lexer.
*)
comment = "#" { comment-character } ;
comment-character = ? any character except "\r" and "\n" ? ;
whitespace = " " | "\t" | "\v" | "\f" ;
