(*
   pyxc.ebnf
   Grammar for chapter 40 — variadic extern functions.
*)

(*
   { } = zero or more (any number of...)
   [ ] = zero or one (optional)
*)

program         = [ eols ] [ top { eols top } ] [ eols ] ;
eols            = eol { eol } ;
top             = typealias | traitdef | structdef | classdef | impldef | functiondef | decoratedfunctiondef | external | toplevelexpr ;
typealias       = "type" name "=" type ;
traitdef        = "trait" name [ "[" name "]" ] ":" eols traitblock ;
traitblock      = indent traitmethodsig { eols traitmethodsig } dedent ;
traitmethodsig  = "def" name "(" [ typedparam { "," typedparam } ] ")" [ "->" type ] ;
structdef       = "struct" name ":" eols structblock ;
classdef        = "class" name [ "(" traitref { "," traitref } ")" ] ":" eols structblock ;
traitref        = name [ "[" type "]" ] ;
impldef         = "impl" traitref "for" name ":" eols implblock ;
implblock       = indent implmethod { eols implmethod } dedent ;
implmethod      = "def" name "(" [ typedparam { "," typedparam } ] ")" [ "->" type ] ":" ( simplestmt | eols block ) ;
structblock     = indent classmember { eols classmember } dedent ;
classmember     = [ visibility ] ( fielddecl | methoddef ) ;
visibility      = "public" | "private" ;
methoddef       = "def" name "(" [ typedparam { "," typedparam } ] ")"
                  [ "->" type ] ":" ( simplestmt | eols block ) ;
fielddecl       = name ":" type ;
functiondef      = "def" functionsignature [ "->" type ] ":" ( simplestmt | eols block ) ;
(* If the return type is omitted, it defaults to None. *)
decoratedfunctiondef    = binarydecorator eols "def" binaryopsignature [ "->" type ] ":" ( simplestmt | eols block )
                | unarydecorator  eols "def" unaryopsignature  [ "->" type ] ":" ( simplestmt | eols block ) ;
binarydecorator = "@" "binary" "(" integer ")" ;
unarydecorator  = "@" "unary" ;
binaryopsignature = customopchar "(" typedparam "," typedparam ")" ;
unaryopsignature  = customopchar "(" typedparam ")" ;
external        = "extern" "def" externfunctionsignature [ "->" type ] ;
toplevelexpr    = expression ;
functionsignature       = name "(" [ typedparam { "," typedparam } ] ")" ;
externfunctionsignature = name "(" [ typedparam { "," typedparam } [ "," "..." ] | "..." ] ")" ;
typedparam      = name ":" type ;
ifstmt          = "if" expression ":" suite
                { eols "elif" expression ":" suite }
                [ eols "else" ":" suite ] ;
whilestmt       = "while" expression ":" suite ;
dowhilestmt     = "do" ":" suite eols "while" expression ;
switchstmt      = "switch" expression ":" eols indent switchbody dedent ;
switchbody      = switchcase { eols switchcase } [ eols defaultcase ] ;
switchcase      = "case" switchint { "," switchint } ":" suite ;
defaultcase     = "default" ":" suite ;
forstmt         = "for"
                  ( "var" name ":" type | name )
                  "=" expression "," expression "," expression ":" suite ;
varstmt         = "var" varbinding { "," varbinding } ;
assignstmt      = lvalue assignop expression ; (* assignment is a statement here *)
simplestmt      = returnstmt | breakstmt | continuestmt | varstmt | assignstmt | expression ;
compoundstmt    = ifstmt | forstmt | whilestmt | dowhilestmt | switchstmt ;
statement       = simplestmt | compoundstmt ;
suite           = simplestmt | compoundstmt | eols block ;
returnstmt      = "return" [ expression ] ;
breakstmt       = "break" ;
continuestmt    = "continue" ;
stmtsep = eols | BLOCK_END ;
block = indent statement { stmtsep statement } dedent ;
expression      = lvalue assignop expression | unaryexpr binoprhs ;
binoprhs        = { binaryop unaryexpr } ;
lvalue          = name | fieldaccess | indexexpr ;
varbinding      = name ":" type [ "=" expression ] ;
unaryexpr       = unaryop unaryexpr | postfixexpr ;
unaryop         = "-" | "!" | "~" | "++" | "--" | userdefunaryop ;
postfixexpr     = primary [ postfixop ] ;
postfixop       = "++" | "--" ;
primary         = castexpr | sizeofexpr | addrexpr | arrayliteral | stringliteral | charliteral | nameexpr | fieldaccess | indexexpr | numberexpr | bool_literal | parenexpr ;
castexpr        = casttype "(" expression ")" ;
sizeofexpr      = "sizeof" "(" type ")" ;
addrexpr        = "addr" "(" lvalue ")" ;
nameexpr  = name | callexpr | methodcallexpr | ctorcallexpr ;
callexpr        = name "(" [ expression { "," expression } ] ")" ;
methodcallexpr  = name "." name "(" [ expression { "," expression } ] ")" ;
ctorcallexpr    = name "(" [ expression { "," expression } ] ")" ;
fieldaccess     = name "." name { "." name } ;
indexexpr       = name "[" expression "]" ;
numberexpr      = number ;
arrayliteral    = "[" [ expression { "," expression } ] "]" ;
stringliteral   = "\"" { ? any char except " and newline ? | escape } "\"" ;
charliteral     = "'" ( ? any char except ' and newline ? | charescape ) "'" ;
escape          = "\\" ( "\\" | "\"" | "n" | "t" | "0" ) ;
charescape      = "\\" ( "\\" | "'" | "n" | "t" | "0" ) ;
parenexpr       = "(" expression ")" ;
binaryop        = builtinbinaryop | userdefbinaryop ;
indent          = INDENT ;
dedent          = DEDENT ;

assignop        = "=" | "+=" | "-=" | "*=" | "/=" | "%=" ;
builtinbinaryop = "+" | "-" | "*" | "/" | "%"
                | "<" | "<=" | ">" | ">=" | "==" | "!="
                | "&&" | "||"
                | "&" | "|" | "^" | "<<" | ">>" ;
userdefbinaryop = ? any opchar defined as a custom binary operator ? ;
userdefunaryop  = ? any opchar defined as a custom unary operator ? ;
customopchar    = ? any opchar that is not "-" or a builtinbinaryop,
                    and not already defined as a custom operator ? ;
opchar          = ? any single ASCII punctuation character ? ;
name      = (letter | "_") { letter | digit | "_" } ;
builtintype     = "int" | "int8" | "int16" | "int32" | "int64"
                | "uint8" | "uint16" | "uint32" | "uint64"
                | "float" | "float32" | "float64"
                | "bool" | "None" ;
aliastype       = name ;
structtype      = name ;
pointertype     = "ptr" "[" type "]" ;
type            = basetype [ arraysuffix ] ;
basetype        = builtintype | aliastype | structtype | pointertype ;
arraysuffix     = "[" integer "]" ;
casttype        = "int" | "int8" | "int16" | "int32" | "int64"
                | "uint8" | "uint16" | "uint32" | "uint64"
                | "float" | "float32" | "float64"
                | "bool" | pointertype ;
integer         = digit { digit } ;
switchint       = [ "-" ] integer ;
number          = digit { digit } [ "." { digit } ]
                | "." digit { digit } ;
bool_literal    = "True" | "False" ;
letter          = "A".."Z" | "a".."z" ;
digit           = "0".."9" ;
eol             = "\r\n" | "\r" | "\n" ;
ws              = " " | "\t" ;
INDENT          = ? synthetic token emitted by lexer ? ;
DEDENT          = ? synthetic token emitted by lexer ? ;

BLOCK_END = ? synthetic token injected into the stream by ParseBlock immediately after it consumes DEDENT ? ;
